import {
  ImportOutlined,
  ExportOutlined,
  PrinterOutlined,
  SettingOutlined,
  FileDoneOutlined,
  AppstoreAddOutlined,
  ShopOutlined,
  FileTextOutlined,
  FileSearchOutlined,
  UserOutlined,
  StockOutlined,
} from "@ant-design/icons";

export const nav = [
  { label: "WIRE ROD", key: "sub1", type: "sub" },
  {
    key: "1",
    icon: <AppstoreAddOutlined className="icon-menubar" />,
    label: "ข้อมูล Wire Rod",
    path: "wirerod",
  },
  {
    key: "2",
    icon: <FileDoneOutlined className="icon-menubar" />,
    label: "ข้อมูลการรับ",
    path: "",
  },
  {
    key: "3",
    icon: <FileDoneOutlined className="icon-menubar" />,
    label: "ข้อมูลการจ่าย",
    path: "",
  },
  {
    key: "4",
    icon: <StockOutlined className="icon-menubar" />,
    label: "สต๊อคคงเหลือ",
    path: "",
  },
  {
    key: "5",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานการรับ",
    path: "",
  },
  {
    key: "6",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานอายุ",
    path: "",
  },
  { label: "ผลิต", key: "sub2", type: "sub" },
  {
    key: "7",
    icon: <FileSearchOutlined className="icon-menubar" />,
    label: "Factory Report",
    path: "",
  },
  {
    key: "8",
    icon: <FileSearchOutlined className="icon-menubar" />,
    label: "Weekly Report",
    path: "",
  },
  {
    key: "9",
    icon: <FileSearchOutlined className="icon-menubar" />,
    label: "Monthly Report",
    path: "",
  },
  {
    key: "10",
    icon: <FileSearchOutlined className="icon-menubar" />,
    label: "Yearly Report",
    path: "",
  },
  {
    key: "11",
    icon: <FileSearchOutlined className="icon-menubar" />,
    label: "QC Report",
    path: "",
  },
  { label: "ขาย", key: "sub3", type: "sub" },
  {
    key: "12",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานยอดขาย - รายวัน",
    path: "",
  },
  {
    key: "13",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานยอดขาย - วันที่ขาย",
    path: "",
  },
  {
    key: "14",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานยอดขาย - Monthly",
    path: "",
  },
  {
    key: "15",
    icon: <UserOutlined className="icon-menubar" />,
    label: "รายงานยอดขาย - ลูกค้า 1",
    path: "",
  },
  {
    key: "16",
    icon: <UserOutlined className="icon-menubar" />,
    label: "รายงานยอดขาย - ลูกค้า 2",
    path: "",
  },
  {
    key: "17",
    icon: <FileTextOutlined className="icon-menubar" />,
    label: "รายงานการสั่งซื้อปัจจุบัน",
    path: "",
  },
];
